'use client'

import { FormEvent, ReactNode, useEffect, useMemo, useState } from 'react'
import { getSession, googleUrl, restoreOAuthSession, rest, signIn, signOut, signUp, supabaseConfigured, upload, signedUrl } from '@/lib/supabase-rest'

type Role = 'creator' | 'brand' | 'admin'
type Profile = { id:string; role:Role; full_name:string; username?:string; avatar_url?:string; bio?:string; location?:string; verified:boolean; rating:number; review_count:number; completion_rate:number; response_rate:number }
type CreatorProfile = { user_id:string; niches:string[]; platforms:string[]; followers:number; engagement_rate:number; average_views:number; starting_rate:number; languages:string[]; availability:string; social_verified:boolean }
type Campaign = { id:string; brand_id:string; title:string; objective?:string; category:string; type:'paid'|'gift'; budget:number; creator_reward:number; location?:string; platforms:string[]; deliverables:string[]; requirements:any; brief?:string; image_url?:string; min_followers:number; deadline?:string; status:string; visibility:string; views:number; saves:number; created_at:string; revision_limit?:number }
type Application = { id:string; campaign_id:string; creator_id:string; message?:string; proposed_rate?:number; brand_remarks?:string; status:string; created_at:string; campaign?:Campaign; creator?:Profile }
type VerificationRequest = { id:string; user_id:string; type:string; documents:any[]; status:string; notes?:string; created_at:string; user?:Profile }
type Review = { id:string; application_id:string; reviewer_id:string; reviewee_id:string; rating:number; comment?:string }
type Notification = { id:string; title:string; body:string; type:string; read_at?:string; created_at:string }
type PaymentSubmission = { id:string; campaign_id:string; brand_id:string; amount:number; transaction_reference?:string; proof_path?:string; status:string; notes?:string; created_at:string; campaign?:Campaign; brand?:Profile }
type Creator = { profile:Profile; creator:CreatorProfile }

const categories = ['Food','Travel','Fashion','Beauty','Lifestyle','Tech','Fitness','Education','Events','Gaming']
const nicheOptions = [
  ['Lifestyle','✨'],['Food','🍔'],['Fashion','👗'],['Beauty','💄'],['Fitness','💪'],['Travel','✈️'],['Tech','📱'],['Gaming','🎮'],['Finance','💰'],['Education','📚']
]
const money = (n:number) => `NPR ${Number(n||0).toLocaleString()}`
const compact = (n:number) => n >= 1000000 ? `${(n/1000000).toFixed(1)}M` : n >= 1000 ? `${(n/1000).toFixed(n>=10000?0:1)}K` : String(n||0)

function Icon({name,size=20}:{name:string;size?:number}) {
  const p:any = {width:size,height:size,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.8,strokeLinecap:'round',strokeLinejoin:'round'}
  const paths:Record<string,ReactNode> = {
    home:<><path d="m3 10 9-7 9 7"/><path d="M5 9v11h14V9"/><path d="M9 20v-6h6v6"/></>,
    search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
    send:<><path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/></>,
    wallet:<><rect x="3" y="5" width="18" height="15" rx="3"/><path d="M3 9h18"/><path d="M16 15h2"/></>,
    user:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,
    heart:<path d="M20.8 8.6c0 5.5-8.8 11-8.8 11S3.2 14.1 3.2 8.6A4.6 4.6 0 0 1 12 6.1a4.6 4.6 0 0 1 8.8 2.5Z"/>,
    bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,
    plus:<><path d="M12 5v14"/><path d="M5 12h14"/></>,
    chevron:<path d="m9 18 6-6-6-6"/>,
    back:<><path d="m15 18-6-6 6-6"/></>,
    check:<path d="m5 12 4 4L19 6"/>,
    star:<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z"/>,
    instagram:<><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.4" cy="6.6" r=".7" fill="currentColor" stroke="none"/></>,
    settings:<><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.8 1.8 0 0 0 .4 2l.1.1-1.8 1.8-.1-.1a1.8 1.8 0 0 0-2-.4 1.8 1.8 0 0 0-1.1 1.6v.2h-2.6V20a1.8 1.8 0 0 0-1.1-1.6 1.8 1.8 0 0 0-2 .4l-.1.1-1.8-1.8.1-.1a1.8 1.8 0 0 0 .4-2A1.8 1.8 0 0 0 6.2 14H6v-2.6h.2A1.8 1.8 0 0 0 7.8 10a1.8 1.8 0 0 0-.4-2l-.1-.1 1.8-1.8.1.1a1.8 1.8 0 0 0 2 .4A1.8 1.8 0 0 0 12.3 5v-.2h2.6V5a1.8 1.8 0 0 0 1.1 1.6 1.8 1.8 0 0 0 2-.4l.1-.1 1.8 1.8-.1.1a1.8 1.8 0 0 0-.4 2 1.8 1.8 0 0 0 1.6 1.1h.2V14H21a1.8 1.8 0 0 0-1.6 1Z"/></>,
    filter:<><path d="M4 6h16"/><path d="M7 12h10"/><path d="M10 18h4"/></>,
    menu:<><path d="M4 6h16"/><path d="M4 12h16"/><path d="M4 18h16"/></>,
    close:<><path d="m6 6 12 12"/><path d="m18 6-12 12"/></>,
    upload:<><path d="M12 16V4"/><path d="m7 9 5-5 5 5"/><path d="M5 20h14"/></>,
    shield:<><path d="M12 3 20 6v5c0 5-3.5 8.5-8 10-4.5-1.5-8-5-8-10V6Z"/><path d="m9 12 2 2 4-4"/></>,
    spark:<><path d="m12 3 1.4 5.6L19 10l-5.6 1.4L12 17l-1.4-5.6L5 10l5.6-1.4Z"/><path d="m19 16 .7 2.3L22 19l-2.3.7L19 22l-.7-2.3L16 19l2.3-.7Z"/></>,
    more:<><circle cx="5" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="19" cy="12" r="1" fill="currentColor" stroke="none"/></>
  }
  return <svg {...p}>{paths[name]||paths.more}</svg>
}

function Logo({light=false}:{light?:boolean}){return <div className={`brand-logo ${light?'brand-logo-light':''}`}><span className={`logo-mark ${light?'logo-mark-light':''}`}><img src="/nepcollab-logo.svg" alt="NepCollab" /></span><span className={light?'text-white':''}>NepCollab</span></div>}
function Button({children,onClick,type='button',secondary=false,disabled=false,className=''}:{children:ReactNode;onClick?:()=>void;type?:'button'|'submit';secondary?:boolean;disabled?:boolean;className?:string}){return <button type={type} onClick={onClick} disabled={disabled} className={`cr-btn ${secondary?'cr-btn-secondary':''} ${className}`}>{children}</button>}
function Input({className='',...p}:any){return <input {...p} className={`cr-input ${className}`}/>}
function Textarea({className='',...p}:any){return <textarea {...p} className={`cr-input cr-textarea ${className}`}/>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="cr-field"><span>{label}</span>{children}</label>}
function Pill({children,tone='purple'}:{children:ReactNode;tone?:'purple'|'green'|'gray'|'pink'|'orange'}){return <span className={`cr-pill ${tone}`}>{children}</span>}
function Avatar({profile,size='md'}:{profile?:Profile|null;size?:'sm'|'md'|'lg'}){const name=profile?.full_name||'User';return profile?.avatar_url?<img src={profile.avatar_url} alt="" className={`avatar ${size}`} />:<div className={`avatar ${size}`}>{name.slice(0,1).toUpperCase()}</div>}
function StatCard({value,label,tone='normal'}:{value:string|number;label:string;tone?:'normal'|'pink'}){return <div className={`stat-card ${tone==='pink'?'stat-pink':''}`}><strong>{value}</strong><span>{label}</span></div>}
function Empty({text,icon='spark'}:{text:string;icon?:string}){return <div className="empty-state"><Icon name={icon} size={24}/><p>{text}</p></div>}

export default function Home(){
  const [session,setSession] = useState<any>(getSession())
  const [profile,setProfile] = useState<Profile|null>(null)
  const [creator,setCreator] = useState<CreatorProfile|null>(null)
  const [wallet,setWallet] = useState<any>({available:0,pending:0,lifetime_earned:0,lifetime_spent:0})
  const [loading,setLoading] = useState(true)
  const [splash,setSplash] = useState(true)
  const [screen,setScreen] = useState<'welcome'|'login'|'signup'|'niche'|'social'>('welcome')
  const [tab,setTab] = useState('home')
  const [email,setEmail] = useState(''); const [password,setPassword] = useState(''); const [name,setName] = useState(''); const [authRole,setAuthRole] = useState<Role>('creator')
  const [niches,setNiches] = useState<string[]>([]); const [socialPlatform,setSocialPlatform] = useState('Instagram'); const [socialHandle,setSocialHandle] = useState(''); const [socialFollowers,setSocialFollowers] = useState(''); const [socialViews,setSocialViews] = useState(''); const [verificationCode,setVerificationCode] = useState('')
  const [campaigns,setCampaigns] = useState<Campaign[]>([]); const [apps,setApps] = useState<Application[]>([]); const [creators,setCreators] = useState<Creator[]>([]); const [notifications,setNotifications] = useState<Notification[]>([]); const [saved,setSaved] = useState<string[]>([])
  const [query,setQuery] = useState(''); const [cat,setCat] = useState('All'); const [selected,setSelected] = useState<Campaign|null>(null); const [showCreate,setShowCreate] = useState(false); const [showNotifications,setShowNotifications] = useState(false); const [toast,setToast] = useState(''); const [error,setError] = useState('')
  const [submissions,setSubmissions] = useState<any[]>([]); const [verificationRequests,setVerificationRequests] = useState<VerificationRequest[]>([]); const [reviews,setReviews] = useState<Review[]>([]); const [socialAccounts,setSocialAccounts] = useState<any[]>([]); const [verificationAdminHandle,setVerificationAdminHandle] = useState('@nepcollab.app'); const [reviewTarget,setReviewTarget] = useState<any>(null); const [submitApp,setSubmitApp] = useState<Application|null>(null); const [submissionUrl,setSubmissionUrl] = useState(''); const [messages,setMessages] = useState<any[]>([]); const [messageText,setMessageText] = useState(''); const [activeConversation,setActiveConversation] = useState<any>(null)
  const [paymentSubmissions,setPaymentSubmissions] = useState<PaymentSubmission[]>([]); const [paymentSettings,setPaymentSettings] = useState({fee:0,qrUrl:'',enabled:false}); const [showPayment,setShowPayment] = useState<Campaign|null>(null)

  const notify=(s:string)=>{setToast(s);window.setTimeout(()=>setToast(''),2800)}

  async function load(){
    if(!session){setLoading(false);return}
    try{
      const ps=await rest<Profile[]>(`profiles?select=*&id=eq.${session.user.id}&limit=1`); let p=ps?.[0];
      const pendingRole=typeof window!=='undefined'?localStorage.getItem('nepcollab_pending_role'):null;
      const userCreatedAt=session.user.created_at?new Date(session.user.created_at).getTime():0; const isFreshUser=userCreatedAt>0 && (Date.now()-userCreatedAt)<10*60*1000;
      if(p && pendingRole && isFreshUser && (pendingRole==='creator'||pendingRole==='brand') && p.role!==pendingRole){ await rest(`profiles?id=eq.${p.id}`,{method:'PATCH',body:JSON.stringify({role:pendingRole}),headers:{Prefer:'return=minimal'}}); p={...p,role:pendingRole as Role}; localStorage.removeItem('nepcollab_pending_role') } else if(pendingRole && !isFreshUser && typeof window!=='undefined'){localStorage.removeItem('nepcollab_pending_role')}
      if(!p){setProfile(null);setLoading(false);return}
      setProfile(p)
      const cp=await rest<CreatorProfile[]>(`creator_profiles?select=*&user_id=eq.${p.id}&limit=1`); setCreator(cp?.[0]||null)
      const ws=await rest<any[]>(`wallets?select=*&user_id=eq.${p.id}&limit=1`); if(ws?.[0])setWallet(ws[0])
      const publicCampaigns=await rest<Campaign[]>(`campaigns?select=*&status=eq.active&visibility=eq.public&order=created_at.desc`); setCampaigns(publicCampaigns||[])
      const ap=await rest<Application[]>(`applications?select=*,campaign:campaigns(*)&creator_id=eq.${p.id}&order=created_at.desc`); setApps(ap||[])
      const sv=await rest<any[]>(`saved_campaigns?select=campaign_id&user_id=eq.${p.id}`); setSaved((sv||[]).map(x=>x.campaign_id))
      const ns=await rest<Notification[]>(`notifications?select=*&user_id=eq.${p.id}&order=created_at.desc&limit=60`); setNotifications(ns||[])
      const rv=await rest<Review[]>(`reviews?select=*&reviewer_id=eq.${p.id}`); setReviews(rv||[])
      const sa=await rest<any[]>(`social_accounts?select=*&user_id=eq.${p.id}&order=created_at.asc`); setSocialAccounts(sa||[])
      const va=await rest<any[]>(`platform_settings?select=key,value&key=eq.social_verification_admin&limit=1`); if(va?.[0]?.value)setVerificationAdminHandle(va[0].value)
      const paymentSettingsRows=await rest<any[]>(`platform_settings?select=key,value&key=in.(platform_fee_npr,payment_qr_url,payment_enabled)`); const pset:any={fee:0,qrUrl:'',enabled:false}; (paymentSettingsRows||[]).forEach((x:any)=>{if(x.key==='platform_fee_npr')pset.fee=Number(x.value||0);if(x.key==='payment_qr_url')pset.qrUrl=String(x.value||'');if(x.key==='payment_enabled')pset.enabled=String(x.value)==='true'}); setPaymentSettings(pset); const pay=await rest<PaymentSubmission[]>(`payment_submissions?select=*,campaign:campaigns(*),brand:profiles(*)&order=created_at.desc&limit=100`); setPaymentSubmissions(pay||[]);
            if(p.role==='brand'){
        const owned=await rest<Campaign[]>(`campaigns?select=*&brand_id=eq.${p.id}&order=created_at.desc`); setCampaigns(owned||[])
        const ss=await rest<any[]>(`submissions?select=*,application:applications(*,campaign:campaigns(*),creator:profiles(*))&order=created_at.desc`); setSubmissions(ss||[])
        const brandApps=await rest<Application[]>(`applications?select=*,campaign:campaigns(*),creator:profiles(*)&order=created_at.desc`); setApps((brandApps||[]).filter((a:any)=>a.campaign?.brand_id===p.id))
        const bp=await rest<any[]>(`brand_profiles?select=*&user_id=eq.${p.id}&limit=1`); if(!bp?.length)await rest('brand_profiles',{method:'POST',body:JSON.stringify({user_id:p.id,business_name:p.full_name,category:'Business'}),headers:{Prefer:'return=minimal'}})
      }
      if(p.role==='admin'){
const vr=await rest<VerificationRequest[]>(`verification_requests?select=*,user:profiles(*)&order=created_at.desc`); setVerificationRequests(vr||[]); const ss=await rest<any[]>(`submissions?select=*,application:applications(*,campaign:campaigns(*),creator:profiles(*)&order=created_at.desc`); setSubmissions(ss||[])
      }
      const cps=await rest<any[]>(`creator_profiles?select=*,profile:profiles(*)&order=followers.desc&limit=50`); setCreators((cps||[]).filter(x=>x.profile?.verified).map(x=>({profile:x.profile,creator:x})))
    }catch(e:any){setError(e.message||'Unable to load NepCollab')}
    finally{setLoading(false)}
  }

  useEffect(()=>{const t=window.setTimeout(()=>setSplash(false),900);return()=>window.clearTimeout(t)},[])
  useEffect(()=>{if('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{})},[])
  useEffect(()=>{(async()=>{const restored=await restoreOAuthSession(); if(restored)setSession(restored)})()},[])
  useEffect(()=>{load(); if(session){const t=window.setInterval(load,20000);return()=>window.clearInterval(t)}},[session?.access_token])
  useEffect(()=>{if(!activeConversation?.id)return; const t=window.setInterval(async()=>{try{const ms=await rest<any[]>(`messages?select=*,sender:profiles(*)&conversation_id=eq.${activeConversation.id}&order=created_at.asc&limit=100`);setMessages(ms||[])}catch{}},5000);return()=>window.clearInterval(t)},[activeConversation?.id])

  function continueWithGoogle(role:Role){
    if(!supabaseConfigured){setError('Add Supabase URL and anon key first');return}
    if(typeof window!=='undefined') localStorage.setItem('nepcollab_pending_role',role)
    window.location.assign(googleUrl())
  }
  async function auth(e?:FormEvent){e?.preventDefault();setError('');try{
    if(!supabaseConfigured) throw new Error('Add Supabase URL and anon key to .env.local first')
    if(screen==='login'){const s=await signIn(email,password);setSession(s);setScreen('welcome');notify('Welcome back')}
    else {const s=await signUp(email,password,name,authRole); if(s){setSession(s); if(authRole==='creator')setScreen('niche'); else setScreen('social'); notify('Account created')} else notify('Check your email to confirm your account, then log in')}
  }catch(e:any){setError(e.message)}}
  async function finishNiche(){
    if(!profile || niches.length===0)return
    try{await rest('creator_profiles',{method:'POST',body:JSON.stringify({user_id:profile.id,niches,platforms:['Instagram','TikTok','Facebook'],followers:0,average_views:0,engagement_rate:0,starting_rate:0,availability:'available',social_verified:false}),headers:{Prefer:'return=minimal'}});setCreator({user_id:profile.id,niches,platforms:['Instagram','TikTok','Facebook'],followers:0,average_views:0,engagement_rate:0,starting_rate:0,languages:['Nepali','English'],availability:'available',social_verified:false});setScreen('social')}catch(e:any){setError(e.message)}}
  async function submitSocialVerification(codeFromUi?:string){
    if(!profile || !socialHandle.trim())return
    const clean=socialHandle.replace(/^@/,'').trim(); const code=codeFromUi||verificationCode||Math.random().toString(36).slice(2,8).toUpperCase()
    try{await rest('social_accounts',{method:'POST',body:JSON.stringify({user_id:profile.id,platform:socialPlatform,handle:clean,profile_url:socialPlatform==='Instagram'?`https://instagram.com/${clean}`:socialPlatform==='TikTok'?`https://www.tiktok.com/@${clean}`:`https://facebook.com/${clean}`,followers:Number(socialFollowers||0),verified:false}),headers:{Prefer:'resolution=merge-duplicates,return=minimal'}});
      await rest('verification_requests',{method:'POST',body:JSON.stringify({user_id:profile.id,type:'social',documents:[{platform:socialPlatform,handle:clean,verification_code:code,followers:Number(socialFollowers||0),average_views:Number(socialViews||0)}],status:'pending',notes:`User says the code was sent from the ${socialPlatform} account to the NepCollab admin account.`}),headers:{Prefer:'return=minimal'}});
      setVerificationCode(code); notify(`${socialPlatform} verification submitted — admin has been notified`); setSocialHandle(''); setSocialFollowers(''); setSocialViews(''); setScreen('welcome'); setTab('home'); await load()
    }catch(e:any){setError(e.message)}
  }
  async function reviewVerification(v:VerificationRequest,approve:boolean){if(!profile)return;try{const doc=v.documents?.[0]||{};await rest(`verification_requests?id=eq.${v.id}`,{method:'PATCH',body:JSON.stringify({status:approve?'approved':'rejected',reviewed_by:profile.id,reviewed_at:new Date().toISOString(),notes:approve?'Verified manually by admin':'Verification could not be confirmed.'}),headers:{Prefer:'return=minimal'}});if(doc.platform)await rest(`social_accounts?user_id=eq.${v.user_id}&platform=eq.${encodeURIComponent(doc.platform)}&handle=eq.${encodeURIComponent(doc.handle)}`,{method:'PATCH',body:JSON.stringify({verified:approve}),headers:{Prefer:'return=minimal'}});if(approve){await rest(`profiles?id=eq.${v.user_id}`,{method:'PATCH',body:JSON.stringify({verified:true,verification_status:'verified'}),headers:{Prefer:'return=minimal'}});await rest(`creator_profiles?user_id=eq.${v.user_id}`,{method:'PATCH',body:JSON.stringify({social_verified:true}),headers:{Prefer:'return=minimal'}})}await rest('notifications',{method:'POST',body:JSON.stringify({user_id:v.user_id,type:'verification',title:approve?'Social account verified':'Verification rejected',body:approve?`${doc.platform} account @${doc.handle} is now verified.`:'Please review your social account details and submit again.',data:{verification_id:v.id}})});await load();notify(approve?'Verification approved':'Verification rejected')}catch(e:any){setError(e.message)}}
  async function saveCampaign(id:string){if(!profile)return;try{if(saved.includes(id)){await rest(`saved_campaigns?user_id=eq.${profile.id}&campaign_id=eq.${id}`,{method:'DELETE'});setSaved(s=>s.filter(x=>x!==id))}else{await rest('saved_campaigns',{method:'POST',body:JSON.stringify({user_id:profile.id,campaign_id:id})});setSaved(s=>[...s,id])}}catch(e:any){setError(e.message)}}
  async function apply(c:Campaign){if(!profile)return;try{if(apps.some(a=>a.campaign_id===c.id)){notify('Already applied');return}const a=await rest<Application[]>('applications',{method:'POST',body:JSON.stringify({campaign_id:c.id,creator_id:profile.id,message:'I would love to create this collaboration.'}),headers:{Prefer:'return=representation'}});setApps(x=>[...(a||[]),...x]);setSelected(null);notify('Application sent to the brand')}catch(e:any){setError(e.message)}}
  async function createCampaign(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile)return;const f=new FormData(e.currentTarget);try{const reward=Number(f.get('reward')||0);const type=(f.get('type')||'paid') as 'paid'|'gift';if(type==='paid' && reward<=0) throw new Error('Paid collaborations need a creator reward greater than NPR 0.');const platforms=String(f.get('platforms')||'Instagram,TikTok').split(',').map(x=>x.trim()).filter(Boolean);const requirements={min_followers:Number(f.get('min_followers')||0),remarks:String(f.get('requirements')||'')};const needsPayment=type==='paid' && paymentSettings.enabled && paymentSettings.fee>0; const c=(await rest<Campaign[]>('campaigns',{method:'POST',body:JSON.stringify({brand_id:profile.id,title:f.get('title'),objective:f.get('objective'),category:f.get('category'),type,budget:reward,creator_reward:reward,location:f.get('location'),platforms,deliverables:[String(f.get('deliverable')||'1 Reel')],requirements,revision_limit:Number(f.get('revisions')||1),brief:f.get('brief'),min_followers:Number(f.get('min_followers')||0),deadline:f.get('deadline')||null,status:needsPayment?'pending_payment':'active',visibility:'public'}),headers:{Prefer:'return=representation'}}))[0];setShowCreate(false);await load(); if(needsPayment){setShowPayment(c);notify('Campaign created — payment proof is required before it goes live')}else notify(type==='gift'?'Barter campaign is live':'Campaign is live — no platform fee') }catch(e:any){setError(e.message)}}
  async function submitPaymentProof(campaign:Campaign,file:File,reference:string){if(!profile||!campaign)return;try{if(!file)throw new Error('Upload the payment screenshot.'); if(file.size>5*1024*1024)throw new Error('Payment screenshot must be under 5 MB.'); if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Use PNG, JPG or WEBP for the payment screenshot.'); const path=`${profile.id}/${campaign.id}-${Date.now()}.${file.name.split('.').pop()||'png'}`; await upload('payment-proofs',path,file); await rest('payment_submissions',{method:'POST',body:JSON.stringify({campaign_id:campaign.id,brand_id:profile.id,amount:paymentSettings.fee,transaction_reference:reference.trim(),proof_path:path,status:'pending'}),headers:{Prefer:'return=minimal'}}); await load();setShowPayment(null);notify('Payment proof submitted — admin will review it')}catch(e:any){setError(e.message)}}
  async function reviewPayment(p:PaymentSubmission,approve:boolean){if(!profile)return;try{if(approve){await rest(`payment_submissions?id=eq.${p.id}`,{method:'PATCH',body:JSON.stringify({status:'approved',reviewed_by:profile.id,reviewed_at:new Date().toISOString()}),headers:{Prefer:'return=minimal'}});await rest(`campaigns?id=eq.${p.campaign_id}`,{method:'PATCH',body:JSON.stringify({status:'active'}),headers:{Prefer:'return=minimal'}});await rest('notifications',{method:'POST',body:JSON.stringify({user_id:p.brand_id,type:'payment',title:'Payment approved — campaign is live',body:`Your payment for ${p.campaign?.title||'your campaign'} was verified.`,data:{payment_id:p.id,campaign_id:p.campaign_id}})});}else{await rest(`payment_submissions?id=eq.${p.id}`,{method:'PATCH',body:JSON.stringify({status:'rejected',reviewed_by:profile.id,reviewed_at:new Date().toISOString(),notes:'Please upload a clearer payment proof and transaction reference.'}),headers:{Prefer:'return=minimal'}});await rest('notifications',{method:'POST',body:JSON.stringify({user_id:p.brand_id,type:'payment',title:'Payment proof needs attention',body:'Please re-upload a clear payment screenshot and transaction reference.',data:{payment_id:p.id,campaign_id:p.campaign_id}})});}await load();notify(approve?'Payment approved — campaign is live':'Payment rejected — brand notified')}catch(e:any){setError(e.message)}}
  async function openPaymentProof(p:PaymentSubmission){try{const url=await signedUrl('payment-proofs',p.proof_path||'',1800);window.open(url,'_blank','noopener,noreferrer')}catch(e:any){setError(e.message)}}
  async function updateApplicationRemarks(id:string,remarks:string){try{await rest(`applications?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({brand_remarks:remarks}),headers:{Prefer:'return=minimal'}});await load();notify('Remarks saved')}catch(e:any){setError(e.message)}}
  async function reviewApplication(a:Application,accept:boolean){try{await rest(`applications?id=eq.${a.id}`,{method:'PATCH',body:JSON.stringify({status:accept?'accepted':'rejected'}),headers:{Prefer:'return=minimal'}});await load();notify(accept?'Creator accepted':'Application rejected')}catch(e:any){setError(e.message)}}
  async function submitContent(){if(!submitApp||!submissionUrl)return;try{await rest('submissions',{method:'POST',body:JSON.stringify({application_id:submitApp.id,creator_id:profile!.id,url:submissionUrl,status:'submitted'})});await rest(`applications?id=eq.${submitApp.id}`,{method:'PATCH',body:JSON.stringify({status:'submitted'}),headers:{Prefer:'return=minimal'}});setSubmitApp(null);setSubmissionUrl('');await load();notify('Content submitted for brand review')}catch(e:any){setError(e.message)}}
  async function reviewSubmission(s:any,approve:boolean){try{await rest(`submissions?id=eq.${s.id}`,{method:'PATCH',body:JSON.stringify({status:approve?'approved':'revision',feedback:approve?'Brand approved.':'Please make the requested revision.'}),headers:{Prefer:'return=minimal'}});await rest(`applications?id=eq.${s.application_id}`,{method:'PATCH',body:JSON.stringify({status:approve?'submitted':'revision'}),headers:{Prefer:'return=minimal'}});await load();notify(approve?'Brand approved — waiting for admin verification':'Revision requested')}catch(e:any){setError(e.message)}}
  async function adminVerifySubmission(s:any){if(!profile)return;try{await rest(`submissions?id=eq.${s.id}`,{method:'PATCH',body:JSON.stringify({status:'approved',admin_verified:true,admin_verified_at:new Date().toISOString(),admin_verified_by:profile.id}),headers:{Prefer:'return=minimal'}});await rest(`applications?id=eq.${s.application_id}`,{method:'PATCH',body:JSON.stringify({status:'completed'}),headers:{Prefer:'return=minimal'}});const amount=s.application?.campaign?.creator_reward||0; if(amount>0){const existing=await rest<any[]>(`transactions?select=id&application_id=eq.${s.application_id}&type=eq.creator_payout&limit=1`); if(!existing?.length) await rest('transactions',{method:'POST',body:JSON.stringify({user_id:s.creator_id,campaign_id:s.application?.campaign_id,application_id:s.application_id,type:'creator_payout',amount,status:'paid',provider:'manual',provider_reference:'MANUAL-'+Date.now(),paid_at:new Date().toISOString()}),headers:{Prefer:'return=minimal'}}); }await rest('notifications',{method:'POST',body:JSON.stringify({user_id:s.creator_id,type:'payout',title:'Collaboration verified & reward released',body:`Your work was verified by NepCollab. ${amount?`NPR ${amount.toLocaleString()} reward recorded.`:'Your barter collaboration is complete.'}`,data:{submission_id:s.id}})});await load();notify('Work verified and reward recorded')}catch(e:any){setError(e.message)}}
  async function submitReview(applicationId:string,revieweeId:string,rating:number,comment:string){if(!profile)return;try{await rest('reviews',{method:'POST',body:JSON.stringify({application_id:applicationId,campaign_id:(apps.find(a=>a.id===applicationId) as any)?.campaign_id||undefined,reviewer_id:profile.id,reviewee_id:revieweeId,rating,comment})});await load();notify('Review published')}catch(e:any){setError(e.message)}}
  async function markNotificationRead(id:string){await rest(`notifications?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({read_at:new Date().toISOString()})});setNotifications(n=>n.map(x=>x.id===id?{...x,read_at:new Date().toISOString()}:x))}
  async function startChat(targetId:string,campaignId?:string){if(!profile)return;try{let q=`conversations?select=*&${campaignId?`campaign_id=eq.${campaignId}&`:''}order=created_at.desc&limit=20`;const convs=await rest<any[]>(q);let conv=convs?.find((c:any)=>c.campaign_id===campaignId);if(!conv){conv=(await rest<any[]>('conversations',{method:'POST',body:JSON.stringify({campaign_id:campaignId||null}),headers:{Prefer:'return=representation'}}))[0];if(conv?.id){await rest('conversation_members',{method:'POST',body:JSON.stringify({conversation_id:conv.id,user_id:profile.id}),headers:{Prefer:'return=minimal'}});await rest('conversation_members',{method:'POST',body:JSON.stringify({conversation_id:conv.id,user_id:targetId}),headers:{Prefer:'return=minimal'}})}}setActiveConversation(conv||null);if(conv?.id){const ms=await rest<any[]>(`messages?select=*,sender:profiles(*)&conversation_id=eq.${conv.id}&order=created_at.asc&limit=100`);setMessages(ms||[])}setTab('messages');notify('Conversation opened')}catch(e:any){setError(e.message)}}
  async function sendMessage(){if(!profile||!activeConversation?.id||!messageText.trim())return;try{const m=(await rest<any[]>('messages',{method:'POST',body:JSON.stringify({conversation_id:activeConversation.id,sender_id:profile.id,body:messageText.trim()}),headers:{Prefer:'return=representation'}}))[0];setMessages(x=>[...x,m]);setMessageText('')}catch(e:any){setError(e.message)}}
  const filtered=useMemo(()=>campaigns.filter(c=>(cat==='All'||c.category===cat)&&(`${c.title} ${c.category} ${c.location||''}`).toLowerCase().includes(query.toLowerCase())),[campaigns,query,cat])
  const unread=notifications.filter(n=>!n.read_at).length

  if(splash) return <Splash/>
  if(loading) return <div className="app-loading"><Logo/><div className="spinner"/><p>Loading your workspace…</p></div>
  if(!session) return screen==='welcome'?<Welcome onCreator={()=>continueWithGoogle('creator')} onLogin={()=>setScreen('login')} onBrand={()=>continueWithGoogle('brand')}/>:<Auth screen={screen} setScreen={setScreen} email={email} setEmail={setEmail} password={password} setPassword={setPassword} name={name} setName={setName} role={authRole} setRole={setAuthRole} onSubmit={auth} onGoogle={()=>continueWithGoogle(authRole)} error={error}/>
  if(!profile) return <RoleMissing onLogout={async()=>{await signOut();setSession(null)}}/>
  if(profile.role==='creator' && (!creator || !creator.niches?.length)) return screen==='niche'?<NicheSetup niches={niches} setNiches={setNiches} onContinue={finishNiche} onBack={()=>setScreen('welcome')}/>:<div className="onboarding-guard"><Logo/><p>Let's finish your creator profile.</p><Button onClick={()=>setScreen('niche')}>Continue</Button></div>
  if((profile.role==='creator'||profile.role==='brand') && !socialAccounts.some((a:any)=>a.verified)) return <VerificationGate role={profile.role} onConnect={()=>setScreen('social')} onLogout={async()=>{await signOut();setSession(null)}}/>
  if(screen==='social') return <SocialSetup adminHandle={verificationAdminHandle} platform={socialPlatform} setPlatform={setSocialPlatform} handle={socialHandle} setHandle={setSocialHandle} followers={socialFollowers} setFollowers={setSocialFollowers} views={socialViews} setViews={setSocialViews} code={verificationCode} onContinue={submitSocialVerification} onSkip={()=>{setScreen('welcome');setTab('home')}} role={profile.role}/>

  const creatorNav=[['home','Home','home'],['discover','Discover','search'],['work','Applications','send'],['wallet','Earnings','wallet'],['profile','Profile','user']]
  const brandNav=[['home','Home','home'],['creators','Creators','search'],['campaigns','Campaigns','send'],['messages','Messages','send'],['profile','Profile','user']]
  const adminNav=[['admin','Control','home'],['payments','Payments','wallet'],['verify','Verify','shield'],['users','People','user'],['settings','Settings','settings']]
  const nav=profile.role==='creator'?creatorNav:profile.role==='brand'?brandNav:adminNav

  return <div className="app-shell">
    <header className="app-topbar">
      <button className="topbar-brand" onClick={()=>setTab('home')}><Logo/></button>
      <div className="topbar-actions">
        <button className="icon-btn" onClick={()=>setShowNotifications(v=>!v)} aria-label="Notifications"><Icon name="bell" size={21}/>{unread>0&&<span className="notif-dot">{unread}</span>}</button>
        <button className="top-avatar" onClick={()=>setTab('profile')}><Avatar profile={profile} size="sm"/></button>
      </div>
      {showNotifications&&<div className="notifications-pop"><div className="notifications-head"><strong>Notifications</strong><span>{unread} unread</span></div>{notifications.length?notifications.map(n=><button key={n.id} onClick={()=>markNotificationRead(n.id)} className={`notification-item ${!n.read_at?'unread':''}`}><span className="notification-icon"><Icon name={n.type==='payment'?'wallet':'spark'} size={16}/></span><span><b>{n.title}</b><small>{n.body}</small></span></button>):<Empty text="You're all caught up." icon="bell"/>}</div>}
    </header>

    <main className="app-main">
      {error&&<div className="error-banner">{error}<button onClick={()=>setError('')}><Icon name="close" size={16}/></button></div>}
      {profile.role==='creator' && tab==='home' && <CreatorHome profile={profile} creator={creator!} campaigns={filtered.slice(0,8)} saved={saved} apps={apps} onSave={saveCampaign} onOpen={setSelected} setTab={setTab}/>} 
      {profile.role==='creator' && tab==='discover' && <Discover campaigns={filtered} saved={saved} onSave={saveCampaign} onOpen={setSelected} query={query} setQuery={setQuery} cat={cat} setCat={setCat}/>} 
      {profile.role==='creator' && tab==='work' && <CreatorApplications apps={apps} onSubmit={setSubmitApp} onRate={(applicationId:string,revieweeId:string)=>setReviewTarget({applicationId,revieweeId})} reviews={reviews}/>} 
      {profile.role==='creator' && tab==='wallet' && <CreatorEarnings wallet={wallet}/>} 
      {profile.role==='creator' && tab==='profile' && <CreatorProfileView profile={profile} creator={creator!} apps={apps} socialAccounts={socialAccounts} onSocial={()=>setScreen('social')} onRefresh={load}/>} 
      {profile.role==='brand' && tab==='home' && <BrandHome profile={profile} campaigns={campaigns} apps={apps} onCreate={()=>setShowCreate(true)} setTab={setTab}/>} 
      {profile.role==='brand' && tab==='campaigns' && <BrandCampaigns campaigns={campaigns} apps={apps} submissions={submissions} onCreate={()=>setShowCreate(true)} onReviewApplication={reviewApplication} onRemarks={updateApplicationRemarks} onReviewSubmission={reviewSubmission} onRate={(applicationId:string,revieweeId:string)=>setReviewTarget({applicationId,revieweeId})} reviews={reviews}/>} 
      {profile.role==='brand' && tab==='creators' && <CreatorDirectory creators={creators} onChat={startChat}/>} 
      {profile.role==='brand' && tab==='messages' && <Messages messages={messages} activeConversation={activeConversation} text={messageText} setText={setMessageText} onSend={sendMessage}/>}
      {profile.role==='brand' && tab==='profile' && <SimpleProfile profile={profile} socialAccounts={socialAccounts} onSocial={()=>setScreen('social')} onRefresh={load}/>} 
      {profile.role==='admin' && tab==='admin' && <Admin verificationRequests={verificationRequests} submissions={submissions} onVerify={adminVerifySubmission}/>}
      {profile.role==='admin' && tab==='payments' && <AdminPayments payments={paymentSubmissions} onReview={reviewPayment} onOpen={openPaymentProof}/>}
      {profile.role==='admin' && tab==='verify' && <AdminVerification requests={verificationRequests} onReview={reviewVerification}/>} 
      {profile.role==='admin' && tab==='users' && <CreatorDirectory creators={creators} onChat={startChat}/>} 
      {profile.role==='admin' && tab==='settings' && <AdminSettings/>} 
      {profile.role==='creator' && tab==='messages' && <Messages messages={messages} activeConversation={activeConversation} text={messageText} setText={setMessageText} onSend={sendMessage}/>}
    </main>

    <nav className="bottom-nav">{nav.map(([id,label,icon])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'active':''}><Icon name={icon} size={20}/><span>{label}</span>{id==='messages'&&unread>0&&<i>{unread}</i>}</button>)}</nav>

    {selected&&<CampaignSheet campaign={selected} saved={saved.includes(selected.id)} role={profile.role} onClose={()=>setSelected(null)} onSave={()=>saveCampaign(selected.id)} onApply={()=>apply(selected)} onChat={()=>startChat(selected.brand_id,selected.id)}/>} 
    {showCreate&&<CreateCampaign onClose={()=>setShowCreate(false)} onSubmit={createCampaign}/>} 
    {submitApp&&<SubmitModal app={submitApp} url={submissionUrl} setUrl={setSubmissionUrl} onClose={()=>setSubmitApp(null)} onSubmit={submitContent}/>} {showPayment&&<PaymentModal campaign={showPayment} fee={paymentSettings.fee} qrUrl={paymentSettings.qrUrl} onClose={()=>setShowPayment(null)} onSubmit={submitPaymentProof}/>} 
    {toast&&<div className="toast"><Icon name="check" size={17}/>{toast}</div>}
  </div>
}

function Splash(){return <div className="splash"><div className="splash-orb one"/><div className="splash-orb two"/><div className="splash-center"><Logo light/><p>Create. Connect. Grow.</p></div><div className="splash-spinner"/></div>}

function Welcome({onCreator,onLogin,onBrand}:{onCreator:()=>void;onLogin:()=>void;onBrand:()=>void}){return <div className="marketing"><section className="welcome-card"><div className="welcome-logo"><Logo/></div><div className="welcome-copy"><h1>Turn your content<br/>into income.</h1><p>One simple place to discover creators, launch campaigns and grow through real collaborations across Nepal.</p><div className="welcome-pills"><Pill>💸 Paid collabs</Pill><Pill>🎁 Barter deals</Pill><Pill>🛡️ Verified people</Pill><Pill>✨ 0% platform fee</Pill></div></div><div className="welcome-actions"><Button onClick={onCreator}>Continue as Creator with Google</Button><Button secondary onClick={onBrand}>Continue as Brand with Google</Button><button className="brand-link" onClick={onLogin}>Already have an account? Sign in</button></div></section><section className="feature-strip"><div><span>FIND YOUR FIT</span><h2>Paid, barter<br/>or local deals</h2></div><div className="mock-phone"><div className="mini-screen"><div className="mini-nav">Home <span>Profile</span></div><div className="mini-card"><b>Fresh brand deals</b><small>Matched to your niche</small></div><div className="mini-card"><b>Earn from content</b><small>Simple, transparent rewards</small></div></div></div></section><section className="feature-strip reverse"><div><span>ALWAYS ON</span><h2>Fresh brand deals<br/>every day</h2></div><div className="mock-phone second"><div className="mini-screen"><div className="mini-tabs"><b>All</b><span>Paid</span><span>Barter</span><span>Local</span></div><div className="mini-list"><div/><div/><div/></div></div></div></section></div>}

function Auth({screen,setScreen,email,setEmail,password,setPassword,name,setName,role,setRole,onSubmit,onGoogle,error}:any){return <div className="auth-page"><div className="auth-panel"><button className="back-btn" onClick={()=>setScreen('welcome')}><Icon name="back"/> Back</button><Logo/><div className="auth-copy"><Pill>🇳🇵 Nepal-first creator marketplace</Pill><h1>{screen==='login'?'Welcome back.':'Join NepCollab.'}</h1><p>Sign in with Google for the fastest, simplest experience. Email is available if you prefer it.</p></div>{error&&<div className="error-inline">{error}</div>}<div className="auth-form"><button type="button" className="google-btn google-primary" onClick={onGoogle}><span className="google-g">G</span><span>{screen==='login'?'Continue with Google':'Sign up with Google'}</span></button><div className="auth-divider"><span>or continue with email</span></div><form onSubmit={onSubmit} className="email-form">{screen==='signup'&&<><Field label="Full name"><Input value={name} onChange={(e:any)=>setName(e.target.value)} required placeholder="Your name"/></Field><Field label="I am"><div className="role-toggle"><button type="button" className={role==='creator'?'active':''} onClick={()=>setRole('creator')}>Creator</button><button type="button" className={role==='brand'?'active':''} onClick={()=>setRole('brand')}>Brand</button></div></Field></>}<Field label="Email"><Input type="email" value={email} onChange={(e:any)=>setEmail(e.target.value)} required placeholder="you@example.com"/></Field><Field label="Password"><Input type="password" value={password} onChange={(e:any)=>setPassword(e.target.value)} minLength={8} required placeholder="At least 8 characters"/></Field><Button type="submit">{screen==='login'?'Sign in':'Create account'}</Button></form></div><button className="switch-auth" onClick={()=>setScreen(screen==='login'?'signup':'login')}>{screen==='login'?"New here? Create an account":"Already have an account? Sign in"}</button><small className="legal-note">By continuing, you agree to NepCollab's terms and privacy policy.</small></div></div>}
function NicheSetup({niches,setNiches,onContinue,onBack}:{niches:string[];setNiches:(x:string[])=>void;onContinue:()=>void;onBack:()=>void}){return <div className="setup-page purple"><button className="setup-back" onClick={onBack}><Icon name="back"/></button><div className="setup-copy"><span>SMART MATCHING</span><h1>Pick your niche,<br/>match instantly</h1><p>Pick up to 5 — we'll match you with the right campaigns.</p></div><div className="niche-grid">{nicheOptions.map(([name,emoji])=>{const active=niches.includes(name);return <button key={name} className={`niche-card ${active?'active':''}`} onClick={()=>setNiches(active?niches.filter(x=>x!==name):niches.length<5?[...niches,name]:niches)}><span>{emoji}</span><b>{name}</b>{active&&<i><Icon name="check" size={15}/></i>}</button>})}</div><div className="setup-footer"><Button disabled={!niches.length} onClick={onContinue}>Continue · {niches.length}/5 selected</Button></div></div>}


function VerificationGate({role,onConnect,onLogout}:{role:'creator'|'brand';onConnect:()=>void;onLogout:()=>void}){return <div className="setup-page purple"><div className="setup-copy"><Logo light/><span>TRUSTED {role==='creator'?'CREATOR':'BRAND'}</span><h1>One quick check.<br/>Then you're in.</h1><p>Connect at least one Instagram, TikTok or Facebook account/page. Send the one-time code from that account to NepCollab so an admin can verify ownership.</p></div><div className="card" style={{width:'100%',maxWidth:560}}><div className="settings-card"><div><span className="settings-icon"><Icon name="shield"/></span><div><b>Why we verify</b><small>It keeps creators and brands trustworthy and reduces fake accounts.</small></div></div></div><Button onClick={onConnect}>Connect a social account</Button><button className="brand-link" onClick={onLogout}>Sign out</button></div></div>}

function SocialSetup({adminHandle,platform,setPlatform,handle,setHandle,followers,setFollowers,views,setViews,code,onContinue,onSkip,role}:any){const [localCode,setLocalCode]=useState(code||Math.random().toString(36).slice(2,8).toUpperCase());const platforms=[['Instagram','◎'],['TikTok','♪'],['Facebook','f']];return <div className="setup-page purple instagram-setup"><button className="setup-back" onClick={onSkip}><Icon name="back"/></button><div className="setup-copy"><span>{role==='creator'?'VERIFIED CREATOR':'VERIFIED BRAND'}</span><h1>Connect your pages.<br/>Build instant trust.</h1><p>Choose a page you control. NepCollab never asks for your social password.</p></div><div className="ig-card"><div className="ig-card-head"><span><span className="social-dot compact-dot">{platforms.find(x=>x[0]===platform)?.[1]}</span> Verify your page</span><b>1-time check</b></div><div className="social-tabs">{platforms.map(([name,icon])=><button key={name} className={platform===name?'active':''} onClick={()=>{setPlatform(name);setLocalCode(Math.random().toString(36).slice(2,8).toUpperCase())}}>{icon} {name}</button>)}</div><Field label={`${platform} handle / page name`}><Input value={handle} onChange={(e:any)=>setHandle(e.target.value)} placeholder={platform==='Facebook'?'your-page-name':'@username'}/></Field><div className="two-fields"><Field label="Followers"><Input type="number" value={followers} onChange={(e:any)=>setFollowers(e.target.value)} placeholder="5000"/></Field><Field label="Avg views (optional)"><Input type="number" value={views} onChange={(e:any)=>setViews(e.target.value)} placeholder="20000"/></Field></div><p className="ig-help">Send the code below <strong>from the claimed account/page</strong> to <b>{adminHandle}</b>. This lets an admin verify that you control it.</p><div className="verify-code"><small>Your one-time verification code</small><strong>{localCode}</strong><div><button type="button" onClick={()=>navigator.clipboard?.writeText(localCode)}>Copy code</button><button type="button" onClick={()=>{const urls:any={Instagram:'https://instagram.com',TikTok:'https://tiktok.com',Facebook:'https://facebook.com'};window.open(urls[platform],'_blank')}}>Open {platform}</button></div></div><ol className="steps"><li>Open {platform} and open <b>{adminHandle}</b></li><li>Send <b>{localCode}</b> from your own account/page</li><li>Return here and tap <b>I've sent it</b></li></ol><Button disabled={!handle} onClick={()=>onContinue(localCode)}>I've sent it</Button></div><button className="skip-link" onClick={onSkip}>I'll do this later</button></div>}

function RoleMissing({onLogout}:{onLogout:()=>void}){return <div className="app-loading"><Logo/><h2>Almost there</h2><p>We couldn't load your profile yet.</p><Button onClick={onLogout}>Sign out</Button></div>}

function CreatorHome({profile,creator,campaigns,saved,apps,onSave,onOpen,setTab}:any){const applied=apps.length;const accepted=apps.filter((a:any)=>['accepted','active','submitted','revision'].includes(a.status)).length;const earned=0;return <div className="creator-home"><div className="home-hello"><div><span className="eyebrow">GOOD MORNING</span><h1>Hi, {profile.full_name.split(' ')[0]} 👋</h1><p>Fresh opportunities matched to your profile.</p></div><button className="round-profile" onClick={()=>setTab('profile')}><Avatar profile={profile}/></button></div><div className="stats-row"><StatCard value={applied} label="Applied"/><StatCard value={accepted} label="Accepted"/><StatCard value={money(earned)} label="Earned" tone="pink"/></div><div className="activity-banner"><span className="activity-avatar">{profile.full_name.slice(0,1)}</span><div><b>{accepted?`${accepted} collaboration${accepted>1?'s':''} in progress`:'Your next collab starts here'}</b><small>{creator.niches?.length?creator.niches.join(' · '):'Complete your profile to improve matches.'}</small></div><span className="live-dot">● LIVE</span></div><section className="section-block"><div className="section-head"><div><h2>New opportunities</h2><p>Matched for your niche & location</p></div><button onClick={()=>setTab('discover')}>See all <Icon name="chevron" size={16}/></button></div>{campaigns.length?<div className="campaign-scroll">{campaigns.slice(0,6).map((c:Campaign)=><CampaignCard key={c.id} c={c} saved={saved.includes(c.id)} onSave={()=>onSave(c.id)} onOpen={()=>onOpen(c)}/>)}</div>:<Empty text="No live campaigns yet. Check back soon."/>}</section><section className="section-block"><div className="section-head"><div><h2>Top barter picks</h2><p>Get products, experiences & perks</p></div><button onClick={()=>setTab('discover')}>See all <Icon name="chevron" size={16}/></button></div><div className="barter-card"><div className="barter-icon">🎁</div><div><Pill tone="pink">BARTER</Pill><h3>Free products & local experiences</h3><p>Discover barter campaigns from businesses near you.</p></div><Icon name="chevron"/></div></section></div>}

function CampaignCard({c,saved,onSave,onOpen}:any){return <article className="campaign-card"><div className="campaign-cover"><div className="brand-letter">{c.title.slice(0,1).toUpperCase()}</div><button onClick={onSave} className={`save-btn ${saved?'saved':''}`}><Icon name="heart" size={18}/></button><Pill tone={c.type==='gift'?'pink':'purple'}>{c.type==='gift'?'🎁 BARTER':'PERFORMANCE'}</Pill></div><div className="campaign-body"><div className="campaign-brand">{c.location||'Nepal'} <span>·</span> {c.category}</div><h3>{c.title}</h3><div className="campaign-meta"><span>👥 {c.min_followers?`${compact(c.min_followers)}+ followers`: 'Open to creators'}</span><span>• {c.status==='active'?'Available':'Closed'}</span></div><div className="campaign-bottom"><strong>{c.type==='gift'?'Free product':`Up to ${money(c.creator_reward)}`}</strong><Button onClick={onOpen}>Apply & start</Button></div></div></article>}

function Discover({campaigns,saved,onSave,onOpen,query,setQuery,cat,setCat}:any){return <div className="discover-page"><div className="page-title"><div><span className="eyebrow">DISCOVER</span><h1>Find your next collab</h1><p>Paid, barter and local opportunities.</p></div><button className="filter-round"><Icon name="filter"/></button></div><div className="search-box"><Icon name="search" size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search campaigns, brands, niches…"/></div><div className="filter-scroll"><button className={cat==='All'?'active':''} onClick={()=>setCat('All')}>All</button>{categories.map(c=><button key={c} className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</div><div className="discover-list">{campaigns.map((c:Campaign)=><CampaignCard key={c.id} c={c} saved={saved.includes(c.id)} onSave={()=>onSave(c.id)} onOpen={()=>onOpen(c)}/>)}{!campaigns.length&&<Empty text="No campaigns match your filters." icon="search"/>}</div></div>}

function CreatorApplications({apps,onSubmit,onRate,reviews}:any){return <div className="page-section"><div className="page-title"><div><span className="eyebrow">YOUR WORK</span><h1>Applications</h1><p>Track every collaboration from apply to verified reward.</p></div></div>{apps.length?<div className="work-list">{apps.map((a:any)=><div className="work-card" key={a.id}><div><Pill tone={a.status==='completed'?'green':a.status==='rejected'?'gray':'purple'}>{a.status.toUpperCase()}</Pill><h3>{a.campaign?.title||'Campaign'}</h3><p>{a.campaign?.type==='gift'?'Free product':money(a.campaign?.creator_reward||0)} · {a.campaign?.category}</p>{a.brand_remarks&&<div className="work-remark"><b>Brand remarks</b><span>{a.brand_remarks}</span></div>}</div>{['accepted','active','revision'].includes(a.status)&&<Button onClick={()=>onSubmit(a)}>Submit work</Button>}{a.status==='completed'&&!reviews.some((r:Review)=>r.application_id===a.id)&&<Button secondary onClick={()=>onRate(a.id,a.campaign?.brand_id)}>Rate brand</Button>}</div>)}</div>:<Empty text="You haven't applied to a campaign yet."/>}</div>}

function CreatorEarnings({wallet}:any){return <div className="page-section"><span className="eyebrow">EARNINGS</span><h1>Money from your work</h1><p className="muted">Your verified payouts and payment history.</p><div className="wallet-hero"><span>AVAILABLE TO WITHDRAW</span><strong>NPR {Number(wallet?.available||0).toLocaleString()}</strong><small>Available balance</small></div><div className="settings-card"><div><Icon name="shield"/><div><b>Manual payout verification</b><small>Creator payouts are sent by admin through eSewa or bank and recorded here.</small></div></div><Icon name="chevron"/></div></div>}

function CreatorProfileView({profile,creator,apps,socialAccounts,onSocial,onRefresh}:any){const [bio,setBio]=useState(profile.bio||'');const [location,setLocation]=useState(profile.location||'Pokhara, Nepal');const [saving,setSaving]=useState(false);async function save(){setSaving(true);try{await rest(`profiles?id=eq.${profile.id}`,{method:'PATCH',body:JSON.stringify({bio,location}),headers:{Prefer:'return=minimal'}});await onRefresh()}finally{setSaving(false)}}return <div className="profile-page"><div className="profile-hero"><Avatar profile={profile} size="lg"/><h1>{profile.full_name} {profile.verified&&<span className="verified"><Icon name="check" size={13}/></span>}</h1><p>@{profile.username||'username'} · {profile.location||'Nepal'}</p><div className="profile-stats"><span><b>{compact(creator.followers)}</b><small>Followers</small></span><span><b>{compact(creator.average_views)}</b><small>Avg views</small></span><span><b>{apps.filter((a:any)=>a.status==='completed').length}</b><small>Completed</small></span></div></div><div className="profile-tags"><span>Categories</span><div>{creator.niches.map((n:string)=><Pill key={n}>{n}</Pill>)}</div></div><div className="section-block"><div className="section-head"><div><h2>Connected accounts</h2><p>Verify the pages you want brands to trust.</p></div><button onClick={onSocial}>Manage</button></div><div className="social-list">{['Instagram','TikTok','Facebook'].map((platform:string)=>{const a=socialAccounts.find((x:any)=>x.platform===platform);return <button className="connected-account" key={platform} onClick={onSocial}><span className="social-dot">{platform==='Instagram'?'◎':platform==='TikTok'?'♪':'f'}</span><div><b>{platform}{a?.verified?' · verified':''}</b><small>{a?`@${a.handle}`:'Connect this account'}</small></div>{a?.verified?<span className="verified"><Icon name="check" size={13}/></span>:<Icon name="chevron"/>}</button>})}</div></div><div className="settings-card"><div><span className="settings-icon"><Icon name="settings"/></span><div><b>Settings</b><small>Profile, social, support & legal</small></div></div><Icon name="chevron"/></div><div className="profile-edit"><Field label="Bio"><Textarea value={bio} onChange={(e:any)=>setBio(e.target.value)} rows={3} placeholder="Tell brands what you create."/></Field><Field label="Location"><Input value={location} onChange={(e:any)=>setLocation(e.target.value)}/></Field><Button disabled={saving} onClick={save}>{saving?'Saving…':'Save changes'}</Button></div></div>}

function BrandHome({profile,campaigns,apps,onCreate,setTab}:any){const live=campaigns.filter((c:Campaign)=>c.status==='active').length;const pending=apps.filter((a:any)=>a.status==='pending').length;return <div className="brand-home"><div className="brand-hero"><div><span className="eyebrow">BRAND WORKSPACE</span><h1>Grow with creators.</h1><p>Launch a campaign, find the right people, and track every collaboration.</p></div><Button onClick={onCreate}><Icon name="plus" size={18}/> New campaign</Button></div><div className="brand-stats"><StatCard value={live} label="Live campaigns"/><StatCard value={campaigns.length} label="Total campaigns"/><StatCard value={pending} label="Creator applications" tone="pink"/></div><div className="brand-action-grid"><button onClick={()=>setTab('creators')}><span><Icon name="search"/></span><b>Find creators</b><small>Search verified local creators</small></button><button onClick={()=>setTab('campaigns')}><span><Icon name="send"/></span><b>Manage campaigns</b><small>Briefs, applications & content</small></button></div><section className="section-block"><div className="section-head"><div><h2>Your campaigns</h2><p>Everything in one place</p></div><button onClick={()=>setTab('campaigns')}>See all <Icon name="chevron" size={16}/></button></div>{campaigns.length?<div className="brand-campaign-list">{campaigns.slice(0,4).map((c:Campaign)=><div className="brand-campaign-row" key={c.id}><span className="brand-letter">{c.title.slice(0,1)}</span><div><b>{c.title}</b><small>{c.category} · {c.location||'Nepal'}</small></div><Pill tone={c.status==='active'?'green':'gray'}>{c.status}</Pill></div>)}</div>:<Empty text="Create your first campaign."/>}</section></div>}

function BrandCampaigns({campaigns,apps,submissions,onCreate,onReviewApplication,onRemarks,onReviewSubmission,onRate,reviews}:any){const [remarks,setRemarks]=useState<Record<string,string>>({});return <div className="page-section"><div className="page-title"><div><span className="eyebrow">CAMPAIGNS</span><h1>Your collaborations</h1><p>Publish free, review creators, approve work and build your reputation.</p></div><Button onClick={onCreate}><Icon name="plus"/> New</Button></div>{campaigns.length?<div className="brand-campaign-list">{campaigns.map((c:Campaign)=><div className="brand-campaign-row large" key={c.id}><span className="brand-letter">{c.title.slice(0,1)}</span><div className="grow"><b>{c.title}</b><small>{money(c.creator_reward)} · {c.category} · {c.location||'Nepal'} · {c.platforms.join(' / ')}</small></div><Pill tone={c.status==='active'?'green':'gray'}>{c.status}</Pill></div>)}</div>:<Empty text="No campaigns yet. Create your first one."/>}<section className="section-block"><div className="section-head"><div><h2>Applications & work</h2><p>Accept creators, leave remarks, review submissions.</p></div></div>{apps.length?apps.map((a:any)=>{const sub=submissions.find((x:any)=>x.application_id===a.id);const canRate=a.status==='completed'&&!reviews.some((r:Review)=>r.application_id===a.id);return <div className="workflow-card" key={a.id}><div className="workflow-head"><Avatar profile={a.creator} size="sm"/><div className="grow"><b>{a.creator?.full_name||'Creator'}</b><small>{a.campaign?.title} · {a.campaign?.category}</small></div><Pill tone={a.status==='completed'?'green':a.status==='rejected'?'gray':'purple'}>{a.status}</Pill></div>{a.status==='pending'&&<div className="workflow-actions"><Button onClick={()=>onReviewApplication(a,true)}>Accept</Button><Button secondary onClick={()=>onReviewApplication(a,false)}>Decline</Button></div>}{['accepted','submitted','revision'].includes(a.status)&&<div className="remark-box"><Field label="Brand remarks / requirements for this creator"><Textarea rows={2} value={remarks[a.id]??a.brand_remarks??''} onChange={(e:any)=>setRemarks({...remarks,[a.id]:e.target.value})} placeholder="Specific feedback, shot list, talking points…"/></Field><Button secondary onClick={()=>onRemarks(a.id,remarks[a.id]??a.brand_remarks??'')}>Save remarks</Button></div>}{sub&&<div className="submission-box"><div><b>Submitted work</b><a href={sub.url} target="_blank" rel="noreferrer">Open deliverable ↗</a></div><Pill tone={sub.status==='approved'?'green':sub.status==='revision'?'orange':'purple'}>{sub.status}</Pill>{sub.status==='submitted'&&<div className="workflow-actions"><Button onClick={()=>onReviewSubmission(sub,true)}>Approve work</Button><Button secondary onClick={()=>onReviewSubmission(sub,false)}>Request revision</Button></div>}</div>}{canRate&&<Button secondary onClick={()=>onRate(a.id,a.creator_id)}>Rate creator</Button>}</div>}) : <Empty text="Applications will appear here when creators apply."/>}</section></div>}

function CreatorDirectory({creators,onChat}:any){return <div className="page-section"><div className="page-title"><div><span className="eyebrow">CREATOR DISCOVERY</span><h1>Find creators</h1><p>Verified and rising creators in your marketplace.</p></div></div><div className="creator-grid">{creators.map((u:Creator)=><div className="creator-card" key={u.profile.id}><Avatar profile={u.profile} size="md"/><div className="creator-card-head"><div><b>{u.profile.full_name}</b><small>{u.profile.location||'Nepal'}</small></div>{u.creator.social_verified&&<span className="verified"><Icon name="check" size={12}/></span>}</div><div className="creator-tags">{u.creator.niches.slice(0,4).map(n=><Pill key={n}>{n}</Pill>)}</div><div className="creator-metrics"><span><b>{compact(u.creator.followers)}</b><small>Followers</small></span><span><b>{u.creator.engagement_rate}%</b><small>Engagement</small></span><span><b>{u.profile.rating||0}★</b><small>Rating</small></span></div><Button secondary onClick={()=>onChat(u.profile.id)}>Message</Button></div>)}</div>{!creators.length&&<Empty text="Creator profiles will appear here as people join."/>}</div>}

function Messages({messages,activeConversation,text,setText,onSend}:any){return <div className="page-section"><span className="eyebrow">MESSAGES</span><h1>Collaborate in one place.</h1><p className="muted">Campaign conversations stay attached to the work.</p><div className="messages-panel">{activeConversation?<><div className="message-list">{messages.length?messages.map((m:any)=><div key={m.id} className={`message-bubble ${m.sender_id===getSession()?.user.id?'mine':''}`}><span>{m.body}</span><small>{new Date(m.created_at).toLocaleString()}</small></div>):<Empty text="Start the conversation." icon="send"/>}</div><div className="message-compose"><Input value={text} onChange={(e:any)=>setText(e.target.value)} placeholder="Write a message…" onKeyDown={(e:any)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();onSend()}}}/><Button onClick={onSend}><Icon name="send" size={16}/> Send</Button></div></>:<div className="messages-empty"><Icon name="send" size={28}/><h3>No conversation selected</h3><p>Open a campaign or creator profile to start a collaboration.</p></div>}</div></div>}

function SimpleProfile({profile,onRefresh}:any){const [bio,setBio]=useState(profile.bio||'');const [location,setLocation]=useState(profile.location||'Pokhara, Nepal');const save=async()=>{await rest(`profiles?id=eq.${profile.id}`,{method:'PATCH',body:JSON.stringify({bio,location}),headers:{Prefer:'return=minimal'}});onRefresh()};return <div className="profile-page"><div className="profile-hero"><Avatar profile={profile} size="lg"/><h1>{profile.full_name}</h1><p>{profile.location||'Nepal'} · Brand account</p></div><div className="settings-card"><div><span className="settings-icon"><Icon name="settings"/></span><div><b>Business profile</b><small>Keep your public brand details accurate.</small></div></div></div><div className="profile-edit"><Field label="Bio"><Textarea value={bio} onChange={(e:any)=>setBio(e.target.value)} rows={4}/></Field><Field label="Location"><Input value={location} onChange={(e:any)=>setLocation(e.target.value)}/></Field><Button onClick={save}>Save changes</Button></div></div>}

function Admin({verificationRequests,submissions,onVerify}:any){const pending=submissions.filter((s:any)=>s.status==='approved'&&!s.admin_verified);return <div className="admin-page"><div className="page-title"><div><span className="eyebrow">ADMIN CONTROL</span><h1>Trust & operations</h1><p>Final verification keeps every collaboration safe.</p></div><Pill tone={pending.length?'orange':'green'}>{pending.length} work to verify</Pill></div><div className="admin-stats"><StatCard value={verificationRequests.filter((v:VerificationRequest)=>v.status==='pending').length} label="Social verification" tone="pink"/><StatCard value={pending.length} label="Work awaiting review"/><StatCard value="NPR 0" label="Platform fee"/></div><div className="admin-card"><div className="admin-card-head"><div><h2>Final work verification</h2><p>Brand approval is required first. Verify here, then the creator reward is recorded.</p></div><span className="secure-chip"><Icon name="shield" size={14}/> Secure</span></div>{pending.length?pending.map((s:any)=><div className="payment-row" key={s.id}><div className="payment-main"><div className="payment-avatar">{(s.creator?.full_name||'C').slice(0,1)}</div><div><b>{s.creator?.full_name||'Creator'}</b><small>{s.application?.campaign?.title||'Collaboration'}</small></div></div><div className="payment-actions"><a href={s.url} target="_blank" rel="noreferrer">Open submitted work ↗</a><div><Button onClick={()=>onVerify(s)}>Verify & reward</Button></div></div></div>):<Empty text="Nothing is waiting for final verification."/>}</div></div>}

function AdminVerification({requests,onReview}:any){const pending=requests.filter((r:VerificationRequest)=>r.status==='pending');return <div className="admin-page"><div className="page-title"><div><span className="eyebrow">VERIFICATION</span><h1>Social accounts</h1><p>Check that the displayed code was sent from the claimed account/page.</p></div><Pill tone={pending.length?'orange':'green'}>{pending.length} pending</Pill></div><div className="admin-card">{pending.length?pending.map((v:VerificationRequest)=>{const d=v.documents?.[0]||{};return <div className="verification-row" key={v.id}><Avatar profile={v.user} size="sm"/><div className="grow"><b>{v.user?.full_name||'User'} · {d.platform}</b><small>@{d.handle} · code <strong>{d.verification_code}</strong> · {Number(d.followers||0).toLocaleString()} followers</small><p>{v.notes}</p></div><div className="workflow-actions"><Button onClick={()=>onReview(v,true)}>Approve</Button><Button secondary onClick={()=>onReview(v,false)}>Reject</Button></div></div>}) : <Empty text="No pending social verification requests." icon="shield"/>}</div></div>}

function AdminPayments({payments,onReview,onOpen}:any){const pending=payments.filter((p:PaymentSubmission)=>p.status==='pending');return <div className="admin-page"><div className="page-title"><div><span className="eyebrow">PAYMENTS</span><h1>QR payment review</h1><p>Review manual payment screenshots before paid campaigns go live.</p></div><Pill tone={pending.length?'orange':'green'}>{pending.length} pending</Pill></div><div className="admin-card">{pending.length?pending.map((p:PaymentSubmission)=><div className="payment-row" key={p.id}><div className="payment-main"><div className="payment-avatar">{(p.brand?.full_name||'B').slice(0,1)}</div><div><b>{p.brand?.full_name||'Brand'}</b><small>{p.campaign?.title||'Campaign'} · {money(p.amount)}</small><small>Ref: {p.transaction_reference||'Not provided'}</small></div></div><div className="payment-actions"><button className="brand-link" onClick={()=>onOpen(p)}>Open proof ↗</button><div><Button onClick={()=>onReview(p,true)}>Approve & go live</Button><Button secondary onClick={()=>onReview(p,false)}>Reject</Button></div></div></div>):<Empty text="No pending QR payments." icon="wallet"/>}</div></div>}

function PaymentModal({campaign,fee,qrUrl,onClose,onSubmit}:any){const [file,setFile]=useState<File|null>(null);const [ref,setRef]=useState('');return <div className="modal-backdrop"><div className="modal-card"><div className="modal-head"><div><Pill tone="orange">PAYMENT VERIFICATION</Pill><h2>Pay before going live</h2><p>Scan the NepCollab QR, then upload your payment screenshot and transaction reference.</p></div><button onClick={onClose}><Icon name="close"/></button></div><div className="payment-qr-box">{qrUrl?<img src={qrUrl} alt="NepCollab payment QR"/>:<div className="qr-placeholder">Admin payment QR not configured yet.</div>}<strong>{money(fee)}</strong></div><Field label="Transaction / reference ID"><Input value={ref} onChange={(e:any)=>setRef(e.target.value)} required placeholder="Enter the payment reference"/></Field><Field label="Payment screenshot"><Input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e:any)=>setFile(e.target.files?.[0]||null)} required/></Field><div className="info-box">Your campaign remains hidden until an admin verifies the payment.</div><div className="modal-actions"><Button disabled={!file||!ref.trim()} onClick={()=>file&&onSubmit(campaign,file,ref)}>Submit payment proof</Button><Button secondary onClick={onClose}>Cancel</Button></div></div></div>}

function AdminSettings(){return <div className="page-section"><span className="eyebrow">SETTINGS</span><h1>Marketplace controls</h1><p className="muted">Everything is free at launch. Admin verification keeps the marketplace trusted.</p><div className="settings-card"><div><span className="settings-icon"><Icon name="shield"/></span><div><b>Free launch mode</b><small>Brands publish campaigns at NPR 0 platform fee. Creator rewards are paid manually after final verification.</small></div></div><Pill tone="green">LIVE</Pill></div><div className="settings-card"><div><span className="settings-icon"><Icon name="instagram"/></span><div><b>Social verification</b><small>Instagram, TikTok and Facebook verification is manual via one-time codes.</small></div></div><Pill tone="purple">Manual</Pill></div></div>}

function CampaignSheet({campaign,saved,role,onClose,onSave,onApply,onChat}:any){return <div className="sheet-backdrop" onClick={onClose}><div className="campaign-sheet" onClick={e=>e.stopPropagation()}><button className="sheet-close" onClick={onClose}><Icon name="close"/></button><div className="sheet-cover"><span>{campaign.title.slice(0,1)}</span></div><div className="sheet-content"><Pill tone={campaign.type==='gift'?'pink':'purple'}>{campaign.type==='gift'?'🎁 BARTER':'PAID COLLAB'}</Pill><h2>{campaign.title}</h2><p>{campaign.location||'Nepal'} · {campaign.category}</p><div className="sheet-price">{campaign.type==='gift'?'Free product':money(campaign.creator_reward)}<small> creator reward</small></div><div className="sheet-info"><span><b>{compact(campaign.min_followers)}</b><small>Min followers</small></span><span><b>{campaign.deliverables?.[0]||'1 Reel'}</b><small>Deliverable</small></span><span><b>{campaign.revision_limit||1}</b><small>Revisions</small></span></div><h3>About this collaboration</h3><p className="sheet-brief">{campaign.brief||campaign.objective||'The brand has not added a detailed brief yet.'}</p><div className="sheet-actions"><Button onClick={onApply}>Apply & start</Button><button className={`heart-action ${saved?'saved':''}`} onClick={onSave}><Icon name="heart"/></button><button className="heart-action" onClick={onChat}><Icon name="send"/></button></div></div></div></div>}

function CreateCampaign({onClose,onSubmit}:any){return <div className="modal-backdrop"><form onSubmit={onSubmit} className="modal-card"><div className="modal-head"><div><Pill tone="green">FREE AT LAUNCH</Pill><h2>Create a campaign</h2><p>Your campaign goes live immediately. There is no platform fee during launch.</p></div><button type="button" onClick={onClose}><Icon name="close"/></button></div><div className="form-grid"><Field label="Campaign title"><Input name="title" required placeholder="e.g. Pokhara food Reel"/></Field><Field label="Category"><select className="cr-input" name="category" defaultValue="Food">{categories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Collab type"><select className="cr-input" name="type"><option value="paid">Paid</option><option value="gift">Barter / gift</option></select></Field><Field label="Creator reward (NPR)"><Input name="reward" type="number" min="0" required placeholder="5000"/></Field><Field label="Location"><Input name="location" defaultValue="Pokhara, Nepal"/></Field><Field label="Minimum followers"><Input name="min_followers" type="number" min="0" defaultValue="1000"/></Field><Field label="Deadline"><Input name="deadline" type="date"/></Field><Field label="Deliverable"><Input name="deliverable" defaultValue="1 Reel"/></Field><Field label="Platforms (comma separated)"><Input name="platforms" defaultValue="Instagram,TikTok"/></Field><Field label="Revision limit"><Input name="revisions" type="number" min="0" max="5" defaultValue="1"/></Field></div><Field label="Objective"><Input name="objective" placeholder="What should this collaboration achieve?"/></Field><Field label="Brief & brand remarks"><Textarea name="brief" rows={5} required placeholder="Product, tone, talking points, must-have remarks, hashtags, location and anything the creator must know."/></Field><Field label="Creator requirements"><Textarea name="requirements" rows={3} placeholder="e.g. Original voice, local audience, must show product in first 5 seconds."/></Field><div className="info-box">Free launch model: brands publish at NPR 0 platform fee. Creator rewards are agreed in the campaign and released after brand + admin verification.</div><div className="modal-actions"><Button type="submit">Publish campaign</Button><Button secondary onClick={onClose}>Cancel</Button></div></form></div>}



function ReviewModal({target,onClose,onSubmit}:{target:any;onClose:()=>void;onSubmit:(rating:number,comment:string)=>void}){const [rating,setRating]=useState(5);const [comment,setComment]=useState('');return <div className="modal-backdrop"><div className="modal-card review-modal"><div className="modal-head"><div><Pill>COLLABORATION REVIEW</Pill><h2>How did it go?</h2><p>Your review helps the marketplace get better.</p></div><button onClick={onClose}><Icon name="close"/></button></div><div className="rating-stars">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setRating(n)} className={n<=rating?'active':''}>★</button>)}</div><Field label="Review (optional)"><Textarea value={comment} onChange={(e:any)=>setComment(e.target.value)} rows={4} placeholder="Share a helpful, honest review…"/></Field><div className="modal-actions"><Button onClick={()=>onSubmit(rating,comment)}>Publish review</Button><Button secondary onClick={onClose}>Not now</Button></div></div></div>}

function SubmitModal({app,url,setUrl,onClose,onSubmit}:any){return <div className="modal-backdrop"><div className="modal-card"><div className="modal-head"><div><Pill>CONTENT SUBMISSION</Pill><h2>Submit your deliverable</h2><p>{app.campaign?.title}</p></div><button onClick={onClose}><Icon name="close"/></button></div><Field label="Instagram / TikTok / YouTube URL"><Input value={url} onChange={(e:any)=>setUrl(e.target.value)} placeholder="https://instagram.com/reel/..."/></Field><div className="info-box">The brand can approve this content or request a revision. Keep the post public while it is being reviewed.</div><div className="modal-actions"><Button disabled={!url} onClick={onSubmit}>Submit content</Button><Button secondary onClick={onClose}>Cancel</Button></div></div></div>}
