name: Extract project

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract ZIP
        run: |
          mkdir temp
          unzip -o NepCollab-PRODUCTION-V5.2.zip -d temp

          if [ -d "temp/nepcollab" ]; then
            cp -a temp/nepcollab/. .
          else
            cp -a temp/. .
          fi

          rm -rf temp
          rm -f NepCollab-PRODUCTION-V5.2.zip

      - name: Save project
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Extract NepCollab project" || true
          git push
